{
  "name": "fplxplm-chat-app",
  "version": "1.0.0",
  "description": "FPL x PLM Official Chat App dengan Firebase Authentication dan Realtime Database",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "dev": "nodemon server.js"
  },
  "author": "Nama Anda",
  "license": "MIT",
  "dependencies": {
    "express": "^4.18.2",
    "cors": "^2.8.5"
  },
  "devDependencies": {
    "nodemon": "^2.0.22"
  }
}
